### ISSUE TITLE
TS L1 Enhancement - Test Profile Changes - DeepSleep manager

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-deepsleep_manager#7]
This task is to modify the Deepsleep manager L1 concerning the latest Test profile changes if any. If there are no changes concerning the test profile, this Jira can be closed with proper information.

Interface file:
https://github.com/rdkcentral/rdk-halif-deepsleep_manager/tree/develop/include

L1 Code: 
https://github.com/rdkcentral/rdk-halif-test-deepsleep_manager/blob/develop/src/test_l1_deepSleepMgr.c

**Comment by drissya-k** [comment]
There are no changes in deepsleep manager concerning the latest test profile.
