### ISSUE TITLE
VTS L1 Enhancement - Test Profile Changes - DeepSleep Manager

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-deepsleep_manager#9]
This task is to modify the L1 concerning the latest Test profile changes if any. If there are no changes concerning the test profile, this Jira can be closed with proper information.

Interface file:
https://github.com/rdkcentral/rdk-halif-deepsleep_manager/blob/develop/include/deepSleepMgr.h

L1 File:
https://github.com/rdkcentral/rdk-halif-test-deepsleep_manager/blob/develop/src/test_l1_deepSleepMgr.c

**Comment by drissya-k** [comment]
There is no changes in deep sleep manager concerning the latest test profile changes.
